CREATE TABLE user
(
    id        INT PRIMARY KEY AUTO_INCREMENT,
    firstname VARCHAR(64) NOT NULL,
    lastname  VARCHAR(64) NOT NULL,
    username  VARCHAR(64) NOT NULL UNIQUE,
    password  VARCHAR(64) NOT NULL,
    role      VARCHAR(32),
    state     VARCHAR(32) NOT NULL DEFAULT 'UNBLOCKED'
);

CREATE TABLE account
(
    id      BIGINT PRIMARY KEY AUTO_INCREMENT,
    balance DECIMAL(15, 2)       DEFAULT 0,
    state   VARCHAR(32) NOT NULL DEFAULT 'UNBLOCKED',
    user_id INT,
    FOREIGN KEY (user_id) REFERENCES user (id) ON DELETE RESTRICT
) AUTO_INCREMENT = 2620330000000001;

CREATE TABLE card
(
    id         BIGINT PRIMARY KEY AUTO_INCREMENT,
    state      VARCHAR(32) NOT NULL DEFAULT 'UNBLOCKED',
    account_id BIGINT,
    FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE RESTRICT
) AUTO_INCREMENT = 5168000000000001;

CREATE TABLE payment
(
    id           INT PRIMARY KEY AUTO_INCREMENT,
    sum          DECIMAL(15, 2),
    comment      VARCHAR(128),
    status       VARCHAR(32) NOT NULL DEFAULT 'PREPARED',
    lastModified TIMESTAMP            DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    account_id   BIGINT,
    card_id      BIGINT,
    FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE RESTRICT,
    FOREIGN KEY (card_id) REFERENCES card (id) ON DELETE RESTRICT
);

CREATE TABLE request_to_unblock
(
    id            INT PRIMARY KEY AUTO_INCREMENT,
    account_id    BIGINT,
    requestStatus VARCHAR(32) NOT NULL DEFAULT 'NEW',
    timeCreated    TIMESTAMP            DEFAULT CURRENT_TIMESTAMP,
    timeDone      TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    FOREIGN KEY (account_id) REFERENCES account (id) ON DELETE RESTRICT
);